<#
.SYNOPSIS
    Documentation Audit

.DESCRIPTION
    Audits the documentation generated by the Documentation Engine.

.NOTES
    Project : Abhimaan Digital Solutionz
    Module  : Internal Developer Tooling (IDT)
    Version : 1.0.0
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------
# Load Helper Libraries
# ---------------------------------------------------------------------

. "$PSScriptRoot\lib\Logging.ps1"
. "$PSScriptRoot\lib\manifest-helper.ps1"
. "$PSScriptRoot\lib\Validation.ps1"

try {

    Write-Log "Starting Documentation Audit..."

    $manifest = Get-Manifest

    Test-Manifest $manifest | Out-Null
    Test-Templates $manifest | Out-Null

    $passed = 0
    $failed = 0

    foreach ($category in $manifest.Categories) {

        $folder = Join-Path `
            (Get-Location) `
            (Join-Path $manifest.Paths.OutputRoot $category.ToLower())

        $document = Join-Path $folder "README.md"

        if (Test-Path $document) {

            Write-Log "$category : OK" SUCCESS
            $passed++
        }
        else {

            Write-Log "$category : Missing README.md" ERROR
            $failed++
        }
    }

    Write-Host ""
    Write-Host "Documentation Audit Summary" -ForegroundColor Cyan
    Write-Host "---------------------------"
    Write-Host "Passed : $passed"
    Write-Host "Failed : $failed"
    Write-Host ""

    if ($failed -gt 0) {
        Write-Log "Documentation audit failed." ERROR
        exit 1
    }

    Write-Log "Documentation audit completed successfully." SUCCESS

}
catch {

    Write-Log $_.Exception.Message ERROR
    exit 1

}