'use client';

import Link from 'next/link';


type ReportType =
    | 'Sales'
    | 'Leads'
    | 'Revenue'
    | 'Projects'
    | 'Tasks'
    | 'Activities'
    | 'Custom';


interface DashboardReport {

    id: string;

    name: string;

    type: ReportType;

    description?: string;

    generatedAt: string;

    generatedBy?: string;

    totalRecords: number;

}


interface Props {

    reports: DashboardReport[];

}



export default function ReportsTable({
    reports,
}: Props) {


    if (reports.length === 0) {

        return (

            <div className="rounded-xl border p-8 text-center text-muted-foreground">
                No reports found.
            </div>

        );

    }


    return (

        <div className="overflow-x-auto rounded-xl border">

            <table className="w-full">

                <thead>

                    <tr className="border-b bg-muted/40 text-left">

                        <th className="p-3">
                            Report
                        </th>

                        <th className="p-3">
                            Type
                        </th>

                        <th className="p-3">
                            Generated
                        </th>

                        <th className="p-3">
                            Records
                        </th>

                        <th className="p-3">
                            Generated By
                        </th>

                        <th className="p-3 text-right">
                            Actions
                        </th>

                    </tr>

                </thead>


                <tbody>

                    {
                        reports.map(report => (

                            <tr
                                key={report.id}
                                className="border-b hover:bg-muted/30"
                            >

                                <td className="p-3">

                                    <div className="font-medium">
                                        {report.name}
                                    </div>

                                    {
                                        report.description && (

                                            <div className="text-xs text-muted-foreground">
                                                {report.description}
                                            </div>

                                        )
                                    }

                                </td>


                                <td className="p-3">
                                    {report.type}
                                </td>


                                <td className="p-3">
                                    {report.generatedAt}
                                </td>


                                <td className="p-3">
                                    {report.totalRecords}
                                </td>


                                <td className="p-3">
                                    {report.generatedBy ?? '-'}
                                </td>


                                <td className="p-3 text-right">

                                    <Link
                                        href={`/crm/reports/${report.id}`}
                                        className="rounded border px-3 py-1 text-sm"
                                    >
                                        View
                                    </Link>

                                </td>

                            </tr>

                        ))
                    }

                </tbody>

            </table>

        </div>

    );

}