Set-StrictMode -Version Latest

function New-ApiArtifacts {

    param(

        [Parameter(Mandatory = $true)]
        [string]$Module,

        [switch]$Force

    )

    Write-Section "Generating API Layer"

    $ctx = Get-ModuleContext $Module

    Write-Template `
        (Get-ModuleFile $Module "Actions") `
        (Get-ActionsTemplate) `
        $ctx `
        -Force:$Force

    Write-Success "Server Actions Generated"

    Write-Template `
        (Get-ModuleFile $Module "Api") `
        (Get-ApiRouteTemplate) `
        $ctx `
        -Force:$Force

    Write-Success "API Route Generated"

    Write-Template `
        (Get-ModuleFile $Module "ApiItem") `
        (Get-ApiItemRouteTemplate) `
        $ctx `
        -Force:$Force

    Write-Success "API Item Route Generated"

    Write-Template `
        (Get-ModuleFile $Module "Documentation") `
        (Get-DocumentationTemplate) `
        $ctx `
        -Force:$Force

    Write-Success "Documentation Generated"

    Write-Template `
        (Get-ModuleFile $Module "Test") `
        (Get-TestTemplate) `
        $ctx `
        -Force:$Force

    Write-Success "Test Generated"

    Write-Success "API Layer Complete"

}

function Get-ActionsTemplate {

@(
"'use server';",
"",
"import { {{Module}}ServiceInstance } from '@/services/crm/{{Module}}Service';",
"",
"export async function list{{Module}}() {",
"    return {{Module}}ServiceInstance.list();",
"}",
"",
"export async function create{{Module}}(data: unknown) {",
"    return {{Module}}ServiceInstance.create(data);",
"}",
"",
"export async function update{{Module}}(id: string, data: unknown) {",
"    return {{Module}}ServiceInstance.update(id, data);",
"}",
"",
"export async function delete{{Module}}(id: string) {",
"    return {{Module}}ServiceInstance.delete(id);",
"}"
)

}

function Get-ApiRouteTemplate {

@(
"import { NextResponse } from 'next/server';",
"",
"export async function GET() {",
"    return NextResponse.json([]);",
"}",
"",
"export async function POST() {",
"    return NextResponse.json({ success: true });",
"}"
)

}

function Get-ApiItemRouteTemplate {

@(
"import { NextResponse } from 'next/server';",
"",
"export async function GET() {",
"    return NextResponse.json({});",
"}",
"",
"export async function PUT() {",
"    return NextResponse.json({ success: true });",
"}",
"",
"export async function DELETE() {",
"    return NextResponse.json({ success: true });",
"}"
)

}

function Get-DocumentationTemplate {

@(
"# {{Module}}",
"",
"## Overview",
"",
"Generated by CRM Factory.",
"",
"## Features",
"",
"- CRUD",
"- Server Actions",
"- API",
"- Validation",
"- Tests"
)

}

function Get-TestTemplate {

@(
"describe('{{Module}}', () => {",
"",
"    it('should load', () => {",
"        expect(true).toBe(true);",
"    });",
"",
"});"
)

}