# # Generated by create-crm-factory.ps1
Set-StrictMode -Version Latest

function New-TypeArtifact {

    param(
        [string]$Module
    )

    Write-TextFile `
        -Path (Get-ModuleFile $Module "Type") `
        -Content @(
"export interface $Module {",
"    id: string;",
"    createdAt?: string;",
"    updatedAt?: string;",
"}"
)

    Write-Success "Type Generated"

}

function New-RepositoryArtifact {

    param(
        [string]$Module
    )

    Write-TextFile `
        -Path (Get-ModuleFile $Module "Repository") `
        -Content @(
"export class ${Module}Repository {",
"",
"    async findAll() {",
"        return [];",
"    }",
"",
"    async findById() {",
"        return null;",
"    }",
"",
"}",
"",
"export const ${Module}RepositoryInstance = new ${Module}Repository();"
)

    Write-Success "Repository Generated"

}

function New-ServiceArtifact {

    param(
        [string]$Module
    )

    Write-TextFile `
        -Path (Get-ModuleFile $Module "Service") `
        -Content @(
"import { ${Module}RepositoryInstance } from '@/repositories/crm/${Module}Repository';",
"",
"export class ${Module}Service {",
"",
"    async getAll() {",
"        return ${Module}RepositoryInstance.findAll();",
"    }",
"",
"    async getById() {",
"        return ${Module}RepositoryInstance.findById();",
"    }",
"",
"}",
"",
"export const ${Module}ServiceInstance = new ${Module}Service();"
)

    Write-Success "Service Generated"

}

function New-HookArtifact {

    param(
        [string]$Module
    )

    Write-TextFile `
        -Path (Get-ModuleFile $Module "Hook") `
        -Content @(
"export function use$Module() {",
"",
"    return {};",
"",
"}"
)

    Write-Success "Hook Generated"

}

function New-ValidationArtifact {

    param(
        [string]$Module
    )

    Write-TextFile `
        -Path (Get-ModuleFile $Module "Validation") `
        -Content @(
"import { z } from 'zod';",
"",
"export const ${Module}Schema = z.object({",
"    id: z.string().optional()",
"});",
"",
"export type ${Module}Input = z.infer<typeof ${Module}Schema>;"
)

    Write-Success "Validation Generated"

}

function New-CrudArtifacts {

    param(
        [string]$Module
    )

    Write-Section "Generating CRUD Layer"

    New-TypeArtifact $Module

    New-RepositoryArtifact $Module

    New-ServiceArtifact $Module

    New-HookArtifact $Module

    New-ValidationArtifact $Module

    Write-Success "CRUD Layer Complete"

}
