# Placeholder
# Generated by create-crm-factory.ps1
Set-StrictMode -Version Latest

function Get-ProjectPaths {

    $src = Join-Path $Script:ProjectRoot "src"

    return @{

        Src = $src

        App = Join-Path $src "app"

        Api = Join-Path $src "app\api"

        Components = Join-Path $src "components"

        Hooks = Join-Path $src "hooks"

        Repositories = Join-Path $src "repositories"

        Services = Join-Path $src "services"

        Types = Join-Path $src "types"

        Config = Join-Path $src "config"

        Validation = Join-Path $src "lib\validation"

        Docs = Join-Path $Script:ProjectRoot "docs"

        Tests = Join-Path $Script:ProjectRoot "tests"

    }

}

function Get-ModulePaths {

    param(
        [string]$Module
    )

    $route = $Module.ToLower()

    $p = Get-ProjectPaths

    return @{

        Module = $Module

        Route = $route

        App = Join-Path $p.App ("crm\" + $route)

        Api = Join-Path $p.Api ("crm\" + $route)

        Components = Join-Path $p.Components ("crm\" + $route)

        Hooks = Join-Path $p.Hooks "crm"

        Repositories = Join-Path $p.Repositories "crm"

        Services = Join-Path $p.Services "crm"

        Types = Join-Path $p.Types "crm"

        Validation = $p.Validation

        Config = Join-Path $p.Config "crm"

        Docs = Join-Path $p.Docs "crm\modules"

        Tests = Join-Path $p.Tests "crm"

    }

}

function New-ModuleFolders {

    param(
        [string]$Module
    )

    $paths = Get-ModulePaths $Module

    foreach ($key in $paths.Keys) {

        if ($key -eq "Module") { continue }

        if ($key -eq "Route") { continue }

        Ensure-Folder $paths[$key]

    }

    Ensure-Folder (Join-Path $paths.App "new")
    Ensure-Folder (Join-Path $paths.App "[id]")
    Ensure-Folder (Join-Path $paths.App "[id]\edit")
    Ensure-Folder (Join-Path $paths.Api "[id]")

    Write-Success "Module Folder Structure Created"

}

function Get-ModuleFile {

    param(

        [string]$Module,

        [string]$Name

    )

    $paths = Get-ModulePaths $Module

    switch ($Name) {

        "Page" {

            return Join-Path $paths.App "page.tsx"

        }

        "Actions" {

            return Join-Path $paths.App "actions.ts"

        }

        "Repository" {

            return Join-Path $paths.Repositories ($Module + "Repository.ts")

        }

        "Service" {

            return Join-Path $paths.Services ($Module + "Service.ts")

        }

        "Hook" {

            return Join-Path $paths.Hooks ("use" + $Module + ".ts")

        }

        "Type" {

            return Join-Path $paths.Types ($Module + ".ts")

        }

        "Validation" {

            return Join-Path $paths.Validation ($Module + "Schema.ts")

        }

        "DataTable" {

            return Join-Path $paths.Components ($Module + "DataTable.tsx")

        }

        "Columns" {

            return Join-Path $paths.Components ($Module + "Columns.ts")

        }

        "Toolbar" {

            return Join-Path $paths.Components ($Module + "Toolbar.tsx")

        }

        "Filters" {

            return Join-Path $paths.Components ($Module + "Filters.tsx")

        }

        "Form" {

            return Join-Path $paths.Components ($Module + "Form.tsx")

        }

        "Api" {

            return Join-Path $paths.Api "route.ts"

        }

        "ApiItem" {

            return Join-Path $paths.Api "[id]\route.ts"

        }

        "Documentation" {

            return Join-Path $paths.Docs ($Module + ".md")

        }

        "Test" {

            return Join-Path $paths.Tests ($Module + ".test.ts")

        }

        default {

            Stop-Factory "Unknown file request : $Name"

        }

    }

}