# # Generated by create-crm-factory.ps1
Set-StrictMode -Version Latest

function Register-CrmModule {

    param(
        [string]$Module
    )

    $paths = Get-ModulePaths $Module

    Ensure-Folder $paths.Config

    $registry = Join-Path $paths.Config "modules.generated.ts"

    $route = $Module.ToLower()

    $content = @(
"export const crmModules = [",
"    ""$route""",
"] as const;"
    )

    Write-TextFile `
        -Path $registry `
        -Content $content `
        -Force

    Write-Success "CRM Module Registry Updated"

}

function Register-Navigation {

    param(
        [string]$Module
    )

    $paths = Get-ModulePaths $Module

    $file = Join-Path $paths.Config "navigation.generated.ts"

    $route = $Module.ToLower()

    $content = @(
"export const crmNavigation = [",
"    {",
"        title: '$Module',",
"        href: '/crm/$route'",
"    }",
"];"
    )

    Write-TextFile `
        -Path $file `
        -Content $content `
        -Force

    Write-Success "Navigation Generated"

}

function Register-CommandPalette {

    param(
        [string]$Module
    )

    $paths = Get-ModulePaths $Module

    $file = Join-Path $paths.Config "command-palette.generated.ts"

    $route = $Module.ToLower()

    $content = @(
"export const crmCommands = [",
"    {",
"        id: '$route',",
"        title: '$Module',",
"        href: '/crm/$route'",
"    }",
"];"
    )

    Write-TextFile `
        -Path $file `
        -Content $content `
        -Force

    Write-Success "Command Palette Generated"

}

function Register-All {

    param(
        [string]$Module
    )

    Register-CrmModule $Module

    Register-Navigation $Module

    Register-CommandPalette $Module

    Write-Success "All Registrations Completed"

}