# # Generated by create-crm-factory.ps1
Set-StrictMode -Version Latest

function Test-GeneratedModule {

    param(
        [string]$Module
    )

    Write-Section "Verifying Generated Module"

    $checks = @(
        "Page",
        "Actions",
        "Repository",
        "Service",
        "Hook",
        "Type",
        "Validation",
        "DataTable",
        "Columns",
        "Toolbar",
        "Filters",
        "Form",
        "Api",
        "ApiItem",
        "Documentation",
        "Test"
    )

    $failed = $false

    foreach ($item in $checks) {

        $file = Get-ModuleFile `
            -Module $Module `
            -Name $item

        if (Test-Path -LiteralPath $file) {

            Write-Success $item

        }
        else {

            Write-WarningMessage ("Missing : " + $item)

            $failed = $true

        }

    }

    if ($failed) {

        Stop-Factory "Verification Failed."

    }

    Write-Success "Verification Passed"

}

function Invoke-Doctor {

    Write-Section "CRM FACTORY DOCTOR"

    Write-Host ("Factory Version : " + $Script:FactoryVersion)
    Write-Host ("Project Root    : " + $Script:ProjectRoot)
    Write-Host ("Script Root     : " + $Script:ScriptRoot)
    Write-Host ""

    $required = @(
        "common.ps1",
        "crm.ps1",
        "docs.ps1",
        "build.ps1",
        "config.json",
        "lib\filesystem.ps1",
        "lib\templates.ps1",
        "lib\generator.ps1",
        "lib\crud.ps1",
        "lib\api.ps1",
        "lib\registry.ps1",
        "lib\verify.ps1"
    )

    foreach ($file in $required) {

        $path = Join-Path $Script:ScriptRoot $file

        if (Test-Path -LiteralPath $path) {

            Write-Success $file

        }
        else {

            Write-WarningMessage ("Missing : " + $file)

        }

    }

}

function Invoke-Clean {

    Write-Section "Factory Clean"

    Write-Host "Nothing to clean."

    Write-Success "Completed"

}

function Invoke-Sync {

    Write-Section "Factory Sync"

    Write-Host "Synchronization placeholder."

    Write-Success "Completed"

}

function Invoke-Verify {

    param(
        [string]$Module
    )

    Assert-Module $Module

    Test-GeneratedModule $Module

}