$ErrorActionPreference = "Stop"

function Get-ProjectRoot {

    return (Resolve-Path "$PSScriptRoot\..").Path

}

function Ensure-Folder {

    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if ([string]::IsNullOrWhiteSpace($Path)) {
        throw "Ensure-Folder : Path is empty."
    }

    if (!(Test-Path -LiteralPath $Path)) {

        New-Item `
            -ItemType Directory `
            -Path $Path `
            -Force | Out-Null

        Write-Host "[CREATE] $Path"

    }
    else {

        Write-Host "[EXISTS] $Path"

    }

}

function Ensure-File {

    param(

        [Parameter(Mandatory = $true)]
        [string]$Path,

        [string]$Content = ""

    )

    if ([string]::IsNullOrWhiteSpace($Path)) {
        throw "Ensure-File : Path is empty."
    }

    $Parent = Split-Path $Path -Parent

    if (!(Test-Path -LiteralPath $Parent)) {

        New-Item `
            -ItemType Directory `
            -Path $Parent `
            -Force | Out-Null

    }

    if (!(Test-Path -LiteralPath $Path)) {

        Set-Content `
            -LiteralPath $Path `
            -Value $Content `
            -Encoding UTF8

        Write-Host "[CREATE] $Path"

    }
    else {

        Write-Host "[EXISTS] $Path"

    }

}

function Write-Readme {

    param(

        [Parameter(Mandatory = $true)]
        [string]$Folder,

        [Parameter(Mandatory = $true)]
        [string]$Title

    )

    $File = Join-Path $Folder "README.md"

    $Content = @"
# $Title

Generated by Abhimaan CRM Platform Factory.

## Purpose

Describe this module.

## Responsibilities

-

## Dependencies

-

## Notes

-

"@

    Ensure-File `
        -Path $File `
        -Content $Content

}

function Write-Markdown {

    param(

        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$Title

    )

    $Content = @"
# $Title

Status

Draft

Generated by Platform Factory.

"@

    Ensure-File `
        -Path $Path `
        -Content $Content

}

function Write-TypescriptFile {

    param(

        [Parameter(Mandatory = $true)]
        [string]$Path

    )

    Ensure-File `
        -Path $Path `
        -Content "// Generated by Platform Factory`r`nexport {};"

}

function Write-Section {

    param(
        [string]$Title
    )

    Write-Host ""
    Write-Host "============================================"
    Write-Host $Title
    Write-Host "============================================"
    Write-Host ""

}