$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $MyInvocation.MyCommand.Path

$files = @(
    "crm.ps1",
    "docs.ps1",
    "build.ps1",
    "common.ps1",
    "config.json",
    "lib\filesystem.ps1",
    "lib\templates.ps1",
    "lib\generator.ps1",
    "lib\crud.ps1",
    "lib\api.ps1",
    "lib\registry.ps1",
    "lib\verify.ps1"
)

foreach ($file in $files) {

    $path = Join-Path $root $file

    $folder = Split-Path -Parent $path

    if (-not (Test-Path -LiteralPath $folder)) {

        New-Item `
            -ItemType Directory `
            -Path $folder | Out-Null

    }

    if (-not (Test-Path -LiteralPath $path)) {

        if ($file.ToLower().EndsWith(".json")) {

            Set-Content `
                -LiteralPath $path `
                -Encoding UTF8 `
                -Value "{}"

        }
        else {

            Set-Content `
                -LiteralPath $path `
                -Encoding UTF8 `
                -Value @(
"# Placeholder",
"# Generated by create-crm-factory.ps1"
)

        }

        Write-Host "[CREATED] $file" -ForegroundColor Green

    }
    else {

        Write-Host "[EXISTS ] $file" -ForegroundColor Yellow

    }

}

Write-Host ""
Write-Host "CRM Factory skeleton ready." -ForegroundColor Cyan