BEGIN;

-- ============================================================================
-- ADS ENTERPRISE PLATFORM
-- CRM AI FOUNDATION
-- Migration : 020
-- ============================================================================
-- Purpose
-- Enterprise AI intelligence foundation for CRM.
--
-- Supports:
-- AI assistant framework
-- AI recommendations
-- Customer intelligence
-- Sales intelligence
-- Workflow intelligence
-- AI governance
--
-- Principles:
-- Entity driven
-- Organization aware
-- Human controlled AI
-- No autonomous destructive actions
-- Repository/service compatible
-- Future Copilot ready
-- ============================================================================


CREATE SCHEMA IF NOT EXISTS ai;

CREATE SCHEMA IF NOT EXISTS crm;



-- ============================================================================
-- AI ASSISTANTS
-- ============================================================================
-- Configurable AI agents.
--
-- Examples:
-- Sales Copilot
-- Customer Success Assistant
-- Admin Assistant
-- Analytics Assistant
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.assistants (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    organization_id UUID,

    assistant_code TEXT NOT NULL,

    assistant_name TEXT NOT NULL,

    assistant_type TEXT DEFAULT 'GENERAL',

    description TEXT,

    status TEXT DEFAULT 'ACTIVE',

    configuration JSONB DEFAULT '{}'::jsonb,

    capabilities JSONB DEFAULT '{}'::jsonb,

    created_by UUID,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    updated_at TIMESTAMPTZ DEFAULT NOW(),


    CONSTRAINT uq_ai_assistant

    UNIQUE(
        organization_id,
        assistant_code
    )

);



CREATE INDEX IF NOT EXISTS
idx_ai_assistant_type

ON ai.assistants(assistant_type);



CREATE INDEX IF NOT EXISTS
idx_ai_assistant_status

ON ai.assistants(status);



-- ============================================================================
-- AI CONVERSATIONS
-- ============================================================================
-- Stores AI interaction history.
--
-- Used for:
-- Audit
-- Improvement
-- User experience
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.conversations (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    organization_id UUID,

    assistant_id UUID,

    user_id UUID,

    entity_type TEXT,

    entity_id UUID,

    conversation_title TEXT,

    status TEXT DEFAULT 'ACTIVE',

    metadata JSONB DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    updated_at TIMESTAMPTZ DEFAULT NOW()

);



CREATE INDEX IF NOT EXISTS
idx_ai_conversation_entity

ON ai.conversations(entity_type, entity_id);



CREATE INDEX IF NOT EXISTS
idx_ai_conversation_user

ON ai.conversations(user_id);



-- ============================================================================
-- AI MESSAGES
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.messages (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    conversation_id UUID NOT NULL,

    message_role TEXT NOT NULL,

    message_content TEXT NOT NULL,

    model_name TEXT,

    token_usage INTEGER DEFAULT 0,

    confidence_score NUMERIC(5,2),

    metadata JSONB DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ DEFAULT NOW(),


    CONSTRAINT fk_ai_message_conversation

    FOREIGN KEY(conversation_id)

    REFERENCES ai.conversations(id)

    ON DELETE CASCADE

);



CREATE INDEX IF NOT EXISTS
idx_ai_messages_conversation

ON ai.messages(conversation_id);



-- ============================================================================
-- AI RECOMMENDATIONS
-- ============================================================================
-- Business recommendations generated by AI.
--
-- Examples:
-- Next best action
-- Lead priority
-- Customer risk
-- Sales guidance
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.recommendations (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    organization_id UUID NOT NULL,

    entity_type TEXT NOT NULL,

    entity_id UUID NOT NULL,

    recommendation_type TEXT NOT NULL,

    recommendation TEXT NOT NULL,

    priority TEXT DEFAULT 'MEDIUM',

    confidence_score NUMERIC(5,2),

    status TEXT DEFAULT 'NEW',

    accepted BOOLEAN,

    generated_at TIMESTAMPTZ DEFAULT NOW(),

    metadata JSONB DEFAULT '{}'::jsonb

);



CREATE INDEX IF NOT EXISTS
idx_ai_recommendation_entity

ON ai.recommendations(entity_type, entity_id);



CREATE INDEX IF NOT EXISTS
idx_ai_recommendation_status

ON ai.recommendations(status);



-- ============================================================================
-- AI MODEL CONFIGURATION
-- ============================================================================
-- Enterprise AI governance.
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.model_configurations (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    organization_id UUID,

    provider TEXT NOT NULL,

    model_name TEXT NOT NULL,

    purpose TEXT,

    enabled BOOLEAN DEFAULT TRUE,

    configuration JSONB DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    updated_at TIMESTAMPTZ DEFAULT NOW()

);



CREATE INDEX IF NOT EXISTS
idx_ai_model_provider

ON ai.model_configurations(provider);



-- ============================================================================
-- AI AUDIT EVENTS
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.audit_events (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    organization_id UUID,

    user_id UUID,

    entity_type TEXT,

    entity_id UUID,

    action_type TEXT NOT NULL,

    model_name TEXT,

    input_summary TEXT,

    output_summary TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW()

);



CREATE INDEX IF NOT EXISTS
idx_ai_audit_entity

ON ai.audit_events(entity_type, entity_id);



-- ============================================================================
-- UPDATED AT TRIGGERS
-- ============================================================================


DO
$$
DECLARE

    tbl TEXT;

BEGIN


    FOREACH tbl IN ARRAY ARRAY[

        'assistants',

        'conversations',

        'model_configurations'

    ]


    LOOP


        EXECUTE format(

            'DROP TRIGGER IF EXISTS trg_%1$s_updated
             ON ai.%1$s;',

            tbl

        );


        EXECUTE format(

            'CREATE TRIGGER trg_%1$s_updated
             BEFORE UPDATE
             ON ai.%1$s
             FOR EACH ROW
             EXECUTE FUNCTION public.set_updated_at();',

            tbl

        );


    END LOOP;


END;
$$;

BEGIN;

-- ============================================================================
-- ADS ENTERPRISE PLATFORM
-- CRM AI FOUNDATION
-- Migration : 020
-- Part 2
-- ============================================================================
-- Purpose
-- Complete AI business intelligence foundation.
--
-- Adds:
-- Prompt templates
-- Lead intelligence
-- Customer risk scoring
-- Sales recommendations
-- AI workflow actions
-- AI analytics
-- Validation framework
-- Migration tracking
-- ============================================================================



-- ============================================================================
-- AI PROMPT TEMPLATES
-- ============================================================================
-- Reusable enterprise AI instructions.
--
-- Examples:
-- Lead analysis
-- Opportunity summary
-- Customer health
-- Sales coaching
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.prompt_templates (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    organization_id UUID,

    prompt_code TEXT NOT NULL,

    prompt_name TEXT NOT NULL,

    prompt_category TEXT DEFAULT 'GENERAL',

    system_instruction TEXT NOT NULL,

    input_schema JSONB DEFAULT '{}'::jsonb,

    output_schema JSONB DEFAULT '{}'::jsonb,

    active BOOLEAN DEFAULT TRUE,

    created_by UUID,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    updated_at TIMESTAMPTZ DEFAULT NOW(),


    CONSTRAINT uq_ai_prompt_template

    UNIQUE(
        organization_id,
        prompt_code
    )

);



CREATE INDEX IF NOT EXISTS
idx_ai_prompt_category

ON ai.prompt_templates(prompt_category);



-- ============================================================================
-- AI LEAD INTELLIGENCE
-- ============================================================================
-- AI-driven lead scoring foundation.
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.lead_intelligence (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    organization_id UUID NOT NULL,

    lead_id UUID NOT NULL,

    score INTEGER DEFAULT 0,

    qualification TEXT,

    buying_probability NUMERIC(5,2),

    recommended_action TEXT,

    reasoning TEXT,

    generated_at TIMESTAMPTZ DEFAULT NOW(),

    metadata JSONB DEFAULT '{}'::jsonb

);



CREATE INDEX IF NOT EXISTS
idx_ai_lead_intelligence_lead

ON ai.lead_intelligence(lead_id);



-- ============================================================================
-- AI CUSTOMER RISK SCORING
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.customer_risk_scores (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    organization_id UUID NOT NULL,

    entity_type TEXT NOT NULL,

    entity_id UUID NOT NULL,

    risk_level TEXT DEFAULT 'LOW',

    risk_score INTEGER DEFAULT 0,

    risk_factors JSONB DEFAULT '{}'::jsonb,

    recommended_actions JSONB DEFAULT '{}'::jsonb,

    calculated_at TIMESTAMPTZ DEFAULT NOW()

);



CREATE INDEX IF NOT EXISTS
idx_ai_customer_risk_entity

ON ai.customer_risk_scores(entity_type, entity_id);



-- ============================================================================
-- AI SALES INSIGHTS
-- ============================================================================
-- Sales Copilot foundation.
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.sales_insights (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    organization_id UUID NOT NULL,

    opportunity_id UUID,

    insight_type TEXT NOT NULL,

    insight_text TEXT NOT NULL,

    confidence_score NUMERIC(5,2),

    priority TEXT DEFAULT 'MEDIUM',

    status TEXT DEFAULT 'NEW',

    created_at TIMESTAMPTZ DEFAULT NOW()

);



CREATE INDEX IF NOT EXISTS
idx_ai_sales_insight_opportunity

ON ai.sales_insights(opportunity_id);



-- ============================================================================
-- AI WORKFLOW ACTIONS
-- ============================================================================
-- Controlled AI automation.
--
-- AI suggests/actions.
-- Business workflow executes.
-- ============================================================================


CREATE TABLE IF NOT EXISTS ai.workflow_actions (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    organization_id UUID NOT NULL,

    entity_type TEXT NOT NULL,

    entity_id UUID NOT NULL,

    action_type TEXT NOT NULL,

    action_payload JSONB DEFAULT '{}'::jsonb,

    execution_status TEXT DEFAULT 'PENDING',

    approved_by UUID,

    executed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ DEFAULT NOW()

);



CREATE INDEX IF NOT EXISTS
idx_ai_workflow_action_entity

ON ai.workflow_actions(entity_type, entity_id);



-- ============================================================================
-- DEFAULT AI PROMPTS
-- ============================================================================


INSERT INTO ai.prompt_templates
(
    prompt_code,
    prompt_name,
    prompt_category,
    system_instruction
)

VALUES

(
    'LEAD_ANALYSIS',

    'Lead Analysis Assistant',

    'SALES',

    'Analyze lead information and provide qualification insights.'
),


(
    'OPPORTUNITY_SUMMARY',

    'Opportunity Summary Assistant',

    'SALES',

    'Summarize opportunity status, risks and next actions.'
),


(
    'CUSTOMER_HEALTH',

    'Customer Health Assistant',

    'CUSTOMER_SUCCESS',

    'Analyze customer engagement and identify risks.'
),


(
    'SALES_COACH',

    'Sales Coaching Assistant',

    'SALES',

    'Provide sales guidance and recommended actions.'
)


ON CONFLICT(
    organization_id,
    prompt_code
)

DO NOTHING;



-- ============================================================================
-- AI INTELLIGENCE SUMMARY VIEW
-- ============================================================================


CREATE OR REPLACE VIEW ai.v_intelligence_summary AS

SELECT

'LEAD_INTELLIGENCE' AS intelligence_type,

COUNT(*) AS total_records

FROM ai.lead_intelligence



UNION ALL



SELECT

'CUSTOMER_RISK',

COUNT(*)

FROM ai.customer_risk_scores



UNION ALL



SELECT

'SALES_INSIGHTS',

COUNT(*)

FROM ai.sales_insights;



-- ============================================================================
-- AI RECOMMENDATION PERFORMANCE
-- ============================================================================


CREATE OR REPLACE VIEW ai.v_recommendation_performance AS


SELECT

recommendation_type,

COUNT(*) AS total_generated,

COUNT(*) FILTER
(
    WHERE accepted = TRUE
)
AS accepted_count,


ROUND(

COUNT(*) FILTER
(
    WHERE accepted = TRUE
)::numeric

/

NULLIF(
    COUNT(*),
    0
)

* 100,

2

)

AS acceptance_percentage


FROM ai.recommendations


GROUP BY recommendation_type;



-- ============================================================================
-- AI VALIDATION
-- ============================================================================


CREATE OR REPLACE VIEW ai.v_ai_health AS


SELECT

'ASSISTANTS' AS check_name,

COUNT(*) AS total_records,

'PASS' AS status

FROM ai.assistants



UNION ALL



SELECT

'PROMPTS',

COUNT(*),

'PASS'

FROM ai.prompt_templates



UNION ALL



SELECT

'RECOMMENDATIONS',

COUNT(*),

'PASS'

FROM ai.recommendations;



-- ============================================================================
-- UPDATED AT TRIGGERS
-- ============================================================================


DO
$$
BEGIN


    DROP TRIGGER IF EXISTS trg_prompt_templates_updated

    ON ai.prompt_templates;


    CREATE TRIGGER trg_prompt_templates_updated

    BEFORE UPDATE

    ON ai.prompt_templates

    FOR EACH ROW

    EXECUTE FUNCTION public.set_updated_at();


END;
$$;



-- ============================================================================
-- MIGRATION REGISTRY
-- ============================================================================


INSERT INTO rollback.deployment_history
(
    migration_number,
    migration_name,
    deployment_version,
    execution_status,
    rollback_available
)

VALUES

(
    20,
    '020_crm_ai.sql',
    '1.0.0',
    'COMPLETED',
    TRUE
);



COMMIT;